services:
    flagception.configurator.array_configurator:
        class: Flagception\Bundle\FlagceptionBundle\DependencyInjection\Configurator\ArrayConfigurator
        tags:
            - { name: flagception.configurator }

    flagception.configurator.constraint_configurator:
        class: Flagception\Bundle\FlagceptionBundle\DependencyInjection\Configurator\ConstraintConfigurator
        tags:
            - { name: flagception.configurator }

    flagception.configurator.environment_configurator:
        class: Flagception\Bundle\FlagceptionBundle\DependencyInjection\Configurator\EnvironmentConfigurator
        tags:
            - { name: flagception.configurator }

    flagception.configurator.cookie_configurator:
        class: Flagception\Bundle\FlagceptionBundle\DependencyInjection\Configurator\CookieConfigurator
        tags:
            - { name: flagception.configurator }

    flagception.configurator.database_configurator:
        class: Flagception\Bundle\FlagceptionBundle\DependencyInjection\Configurator\DatabaseConfigurator
        tags:
            - { name: flagception.configurator }
