# .github/workflows/code_checks.yaml
name: Code_Checks

on: ["push", "pull_request"]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.0']
        stability: [ prefer-stable ]
        symfony-version: ['4.4', '5.4', '6.2']
        include:
          - php: '7.1'
            stability: prefer-lowest
          - php: '7.2'
            symfony-version: 4.4
          - php: '7.2'
            symfony-version: 5.4
          - php: '7.3'
            symfony-version: 5.4
          - php: '7.4'
            symfony-version: 5.4
          - php: '8.0'
            symfony-version: 5.4
          - php: '8.0'
            symfony-version: 6.0
          - php: '8.1'
            symfony-version: 6.1
          - php: '8.2'
            symfony-version: 6.2

    name: PHP ${{ matrix.php }} - ${{ matrix.symfony-version }} ${{ matrix.stability }} tests
    steps:
      # basically git clone
      - uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      # use PHP of specific version
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pcov, xdebug
          coverage: xdebug

      - name: Install dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony-version }}
        run: |
          composer global config --no-plugins allow-plugins.symfony/flex true
          composer global require --no-progress --no-scripts --no-plugins symfony/flex
          composer update --no-interaction --prefer-dist --optimize-autoloader
          vendor/bin/simple-phpunit install

      - name: Execute tests
        env:
          SYMFONY_DEPRECATIONS_HELPER: 'weak'
        run: ./vendor/bin/simple-phpunit --verbose --coverage-text


  cs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
      - run: composer install --no-progress
      - run: ./vendor/bin/phpcs

  finish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
